version: "3.9"
services:
  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=g2
    ports:
      - "3309:3306"
    restart: unless-stopped

  projet_final:
    container_name: 4twin1-g2-projetfinal
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/g2?createDatabaseIfNotExist=true&userSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    image: rejebAdem-4twin1-g2-projetfinal:1.0
    depends_on:
      - db-mysql